import EzReactTable from "../EzReactTable";
import "../EzReactTable/styles.css"
import React from "react";

const Template = (args) => <EzReactTable {...args} />;

export default {
  title: "Examples",
  component: EzReactTable,
};

export const ColumnPagination = () => {
    return (<div style={{ width: "80%", position: 'relative'}}>
      <Template
      tableHeight={200}
      rowHeight={40}
      showCols={4}
        cols={[
          {
            title: "Index",
            key: "index",
          },
          {
            title: "isActive",
            key: "isActive",
          },
          {
            title: "About",
            key: "about",
          },
          {
            title: "Company",
            key: "company",
          },
          {
            title: "Phone",
            key: "phone",
          },
          {
            title: "Gender",
            key: "gender",
          },
          {
            title: "Balance",
            key: "balance",
          },
          {
            title: "Registered",
            key: "registered",
          },
          {
            title: "Email",
            key: "email",
          }
        ]}
        data={[
          {
            "_id": "6213d2347552a4c1d9cdcab9",
            "index": 0,
            "guid": "7487a232-cf8c-4406-abed-e99329cab541",
            "isActive": true,
            "balance": "$1,368.86",
            "age": 23,
            "eyeColor": "green",
            "name": "Lucy Dillard",
            "gender": "female",
            "company": "ENTROPIX",
            "email": "lucydillard@entropix.com",
            "phone": "+1 (822) 472-2263",
            "address": "129 Rock Street, Cedarville, New Mexico, 8670",
            "about": "Veniam labore labore magna reprehenderit voluptate ea quis. Officia ipsum exercitation anim id sit adipisicing fugiat occaecat occaecat fugiat. Dolor sit laborum officia commodo tempor.\r\n",
            "registered": "2015-08-19T07:51:39 +04:00",
            "latitude": -80.169559,
            "longitude": 63.49259,
            "favoriteFruit": "apple"
          },
          {
            "_id": "6213d234ba657775dfe7228a",
            "index": 1,
            "guid": "470f69a6-18c7-40c6-838e-53ad96515d72",
            "isActive": true,
            "balance": "$2,716.63",
            "age": 27,
            "eyeColor": "green",
            "name": "Aida Guzman",
            "gender": "female",
            "company": "JASPER",
            "email": "aidaguzman@jasper.com",
            "phone": "+1 (899) 437-2384",
            "address": "415 Conduit Boulevard, Worcester, Iowa, 7527",
            "about": "Cillum sit exercitation sit tempor. Cupidatat non tempor aute proident laboris incididunt eiusmod veniam enim. Magna commodo eiusmod cillum consectetur. Ipsum laboris amet fugiat pariatur elit consequat ipsum consequat.\r\n",
            "registered": "2019-06-23T10:17:02 +04:00",
            "latitude": -87.689407,
            "longitude": -105.03528,
            "favoriteFruit": "banana"
          },
          {
            "_id": "6213d2342e0d7ed64c5275d3",
            "index": 2,
            "guid": "a0deb54f-ff58-4c6d-aca8-8d17f26be0c7",
            "isActive": true,
            "balance": "$1,687.75",
            "age": 27,
            "eyeColor": "brown",
            "name": "Brenda Wooten",
            "gender": "female",
            "company": "SLUMBERIA",
            "email": "brendawooten@slumberia.com",
            "phone": "+1 (939) 507-3980",
            "address": "115 Cranberry Street, Windsor, Rhode Island, 3277",
            "about": "Sint laboris ipsum excepteur eu id qui laboris qui. Consequat laborum ad eu do consequat magna commodo. Do aliquip sunt magna quis et velit. Non laboris ut ut aute. Ex sunt ex sunt in ex amet do exercitation consectetur elit pariatur laboris. Dolor ipsum eiusmod tempor tempor elit duis et nostrud dolore sit deserunt anim id adipisicing. Cupidatat ut Lorem adipisicing occaecat.\r\n",
            "registered": "2016-03-29T02:57:38 +04:00",
            "latitude": 67.066069,
            "longitude": -16.595196,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d234ff7bd7c251ec9a63",
            "index": 3,
            "guid": "d34258fc-9367-4996-be03-683c859e37a7",
            "isActive": false,
            "balance": "$3,576.91",
            "age": 31,
            "eyeColor": "blue",
            "name": "Santiago Bird",
            "gender": "male",
            "company": "PHARMACON",
            "email": "santiagobird@pharmacon.com",
            "phone": "+1 (903) 436-3435",
            "address": "299 Butler Street, Hessville, Missouri, 3715",
            "about": "Magna reprehenderit ea aute proident. Nulla sint ea eu ipsum nostrud irure reprehenderit sit quis est laborum elit cillum tempor. Dolor in mollit tempor qui quis elit non officia ut in laborum culpa deserunt aute.\r\n",
            "registered": "2019-09-30T02:29:31 +04:00",
            "latitude": 49.781027,
            "longitude": 169.781229,
            "favoriteFruit": "apple"
          },
          {
            "_id": "6213d2344f18ebbd4ca3ecba",
            "index": 4,
            "guid": "d5c002b6-20ec-42b1-ae0a-cbb108f36434",
            "isActive": false,
            "balance": "$2,568.23",
            "age": 40,
            "eyeColor": "brown",
            "name": "Yesenia Douglas",
            "gender": "female",
            "company": "APEXIA",
            "email": "yeseniadouglas@apexia.com",
            "phone": "+1 (819) 521-2287",
            "address": "253 Albee Square, Rose, Alaska, 947",
            "about": "Aliquip culpa sit nostrud magna anim velit. Fugiat nisi qui velit minim voluptate in ea velit Lorem ad minim commodo esse commodo. Voluptate dolor ut pariatur nostrud. Commodo aute anim irure irure nulla et anim anim nulla laborum consequat. Sint culpa veniam officia amet sit consequat ipsum. Esse cillum duis nostrud pariatur amet.\r\n",
            "registered": "2017-06-08T11:04:01 +04:00",
            "latitude": 63.947181,
            "longitude": -6.298823,
            "favoriteFruit": "banana"
          },
          {
            "_id": "6213d2344c56b5d394c60a84",
            "index": 5,
            "guid": "d4a34ca0-c1b4-4bf2-8ed6-8eee41020a50",
            "isActive": false,
            "balance": "$2,199.74",
            "age": 35,
            "eyeColor": "green",
            "name": "Stark Mooney",
            "gender": "male",
            "company": "ANARCO",
            "email": "starkmooney@anarco.com",
            "phone": "+1 (876) 456-3990",
            "address": "212 Village Road, Stewart, California, 5212",
            "about": "Incididunt veniam ipsum voluptate minim et tempor commodo enim. Nisi id ullamco do velit do consectetur nulla eu incididunt fugiat officia aliqua anim. Cupidatat ullamco elit deserunt aute in sunt consequat sint deserunt aliqua commodo elit eiusmod. Proident proident incididunt exercitation nostrud proident est veniam ea elit minim. Reprehenderit ut fugiat commodo ex.\r\n",
            "registered": "2016-05-09T11:01:01 +04:00",
            "latitude": -19.721977,
            "longitude": -51.664778,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d23424c54abd5b21afa6",
            "index": 6,
            "guid": "260c9ecf-8e71-44bd-89a9-c0f85a92b119",
            "isActive": false,
            "balance": "$3,100.20",
            "age": 29,
            "eyeColor": "blue",
            "name": "Terry Oneill",
            "gender": "female",
            "company": "NIMON",
            "email": "terryoneill@nimon.com",
            "phone": "+1 (944) 434-2112",
            "address": "628 Landis Court, Montura, Montana, 532",
            "about": "Eu ut duis anim amet laborum. Amet dolore eiusmod irure commodo enim qui cupidatat mollit Lorem est. Eiusmod officia nostrud duis in aliquip ad exercitation sint irure reprehenderit enim ut exercitation minim. Nostrud magna sint eiusmod exercitation ut id enim consectetur.\r\n",
            "registered": "2019-03-09T03:57:58 +05:00",
            "latitude": -85.714335,
            "longitude": 63.360859,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d23451a09142c8b0253d",
            "index": 7,
            "guid": "1bcd8a75-62b7-4c43-8364-08eaa185391e",
            "isActive": false,
            "balance": "$2,969.24",
            "age": 28,
            "eyeColor": "brown",
            "name": "Barker Tillman",
            "gender": "male",
            "company": "CONFRENZY",
            "email": "barkertillman@confrenzy.com",
            "phone": "+1 (855) 552-3417",
            "address": "478 Remsen Avenue, Kersey, Virgin Islands, 4129",
            "about": "Occaecat aliqua velit mollit eu proident eiusmod. Consequat et esse ad laborum non dolor laborum proident reprehenderit id. Veniam cupidatat minim qui minim mollit magna quis sint. Adipisicing do excepteur minim tempor minim ad. Proident culpa exercitation culpa id labore ut cupidatat. Amet exercitation sit tempor aliqua enim reprehenderit commodo consequat occaecat minim proident pariatur. Nisi labore ad ullamco velit nisi cillum eiusmod nostrud.\r\n",
            "registered": "2015-11-02T11:31:23 +05:00",
            "latitude": -31.708027,
            "longitude": -37.394326,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d2342ea7bf5697b84f98",
            "index": 8,
            "guid": "7f8c004c-884c-40e5-ac57-ad10a66f3065",
            "isActive": false,
            "balance": "$3,523.92",
            "age": 36,
            "eyeColor": "green",
            "name": "Collins Cain",
            "gender": "male",
            "company": "XUMONK",
            "email": "collinscain@xumonk.com",
            "phone": "+1 (835) 562-2645",
            "address": "418 Lamont Court, Rosburg, Tennessee, 9470",
            "about": "Aliquip excepteur id excepteur anim veniam. Reprehenderit ipsum sit esse irure incididunt velit mollit eu proident. Ullamco quis officia est sit velit anim laboris veniam enim eu ipsum est exercitation qui.\r\n",
            "registered": "2020-12-05T04:24:24 +05:00",
            "latitude": -44.090956,
            "longitude": 49.962998,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d234e7a599ce26aa2052",
            "index": 9,
            "guid": "5411098c-4ac3-4534-ac1d-be60078abd6b",
            "isActive": false,
            "balance": "$2,915.51",
            "age": 25,
            "eyeColor": "green",
            "name": "Carmela Luna",
            "gender": "female",
            "company": "INSURESYS",
            "email": "carmelaluna@insuresys.com",
            "phone": "+1 (969) 573-2240",
            "address": "110 Scholes Street, Eagletown, Pennsylvania, 530",
            "about": "Exercitation dolore non quis commodo proident sint nisi. Adipisicing voluptate aliquip duis sint et consequat officia qui. Cupidatat quis enim nisi irure qui veniam. In aliqua qui magna duis.\r\n",
            "registered": "2017-06-20T12:16:23 +04:00",
            "latitude": -17.406952,
            "longitude": 0.086926,
            "favoriteFruit": "banana"
          },
          {
            "_id": "6213d234162395d4f0de39d5",
            "index": 10,
            "guid": "ab12eaaa-847e-40ef-aac9-77bcfb5e38d6",
            "isActive": false,
            "balance": "$2,418.29",
            "age": 23,
            "eyeColor": "green",
            "name": "Banks Caldwell",
            "gender": "male",
            "company": "ACCIDENCY",
            "email": "bankscaldwell@accidency.com",
            "phone": "+1 (907) 420-3886",
            "address": "666 Bowery Street, Fairhaven, American Samoa, 5828",
            "about": "Nulla magna culpa pariatur non proident ad voluptate incididunt labore aute enim. Mollit nostrud ipsum quis Lorem anim occaecat laboris magna. Mollit sit sint ut consequat est Lorem elit deserunt adipisicing reprehenderit aute. Consequat in do ad minim ullamco veniam cupidatat ad nulla sint. Est mollit pariatur anim qui irure non. Duis proident esse sunt veniam id dolor officia magna id duis reprehenderit. Ipsum aute ipsum sint officia commodo enim magna do eiusmod nostrud.\r\n",
            "registered": "2016-11-16T12:28:09 +05:00",
            "latitude": -83.016905,
            "longitude": 175.679785,
            "favoriteFruit": "banana"
          },
          {
            "_id": "6213d2340532a21532e3ffc7",
            "index": 11,
            "guid": "218413e5-c656-4188-86a3-36b96542fb70",
            "isActive": false,
            "balance": "$3,149.31",
            "age": 28,
            "eyeColor": "green",
            "name": "Cox Suarez",
            "gender": "male",
            "company": "KIOSK",
            "email": "coxsuarez@kiosk.com",
            "phone": "+1 (904) 590-3502",
            "address": "620 Bartlett Place, Clayville, Arizona, 4886",
            "about": "Do proident ea dolor dolor deserunt consequat ullamco voluptate adipisicing tempor voluptate. Aliquip exercitation eiusmod nostrud excepteur laboris do ipsum laborum ut anim do deserunt. Esse qui laboris occaecat voluptate in culpa proident.\r\n",
            "registered": "2021-01-16T11:48:25 +05:00",
            "latitude": -58.878454,
            "longitude": -6.366469,
            "favoriteFruit": "apple"
          },
          {
            "_id": "6213d234495369cd9d63acfc",
            "index": 12,
            "guid": "6c5cd74a-93e0-4aa8-803e-7ad9d67b895a",
            "isActive": true,
            "balance": "$3,772.75",
            "age": 30,
            "eyeColor": "brown",
            "name": "Ware Hinton",
            "gender": "male",
            "company": "BUGSALL",
            "email": "warehinton@bugsall.com",
            "phone": "+1 (921) 405-3158",
            "address": "761 Seba Avenue, Kenvil, Oregon, 6866",
            "about": "Elit ullamco voluptate labore deserunt. Sit dolor adipisicing duis eu eiusmod do nulla consequat. Velit duis cupidatat nisi et esse ex velit labore aute esse. Sint ex ad magna aute pariatur exercitation laboris ea. Cupidatat et non aliquip nostrud elit officia nulla.\r\n",
            "registered": "2015-09-20T10:12:35 +04:00",
            "latitude": 15.446973,
            "longitude": 163.184024,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d234d30ac1980d443718",
            "index": 13,
            "guid": "0355e344-3e91-49a8-af6c-bfb854ee9a98",
            "isActive": true,
            "balance": "$3,749.26",
            "age": 32,
            "eyeColor": "blue",
            "name": "Norton Atkins",
            "gender": "male",
            "company": "NORSUL",
            "email": "nortonatkins@norsul.com",
            "phone": "+1 (808) 595-3247",
            "address": "779 Canal Avenue, Sanders, Florida, 2096",
            "about": "Duis pariatur amet ex consectetur elit. Pariatur laborum esse quis pariatur ad tempor anim dolore. Proident cillum consectetur voluptate nisi in consequat dolor est non Lorem irure commodo. Id id aliquip incididunt do sit qui ad aliquip eu eu cillum adipisicing magna laborum.\r\n",
            "registered": "2020-12-01T09:29:39 +05:00",
            "latitude": -70.904339,
            "longitude": -69.923879,
            "favoriteFruit": "apple"
          },
          {
            "_id": "6213d234ec3fb43ad65c60e3",
            "index": 14,
            "guid": "dcd0c783-2a51-4406-af4f-365dcaa69ecd",
            "isActive": false,
            "balance": "$3,860.37",
            "age": 36,
            "eyeColor": "green",
            "name": "Susanne Duran",
            "gender": "female",
            "company": "RUBADUB",
            "email": "susanneduran@rubadub.com",
            "phone": "+1 (846) 589-2918",
            "address": "275 Roosevelt Court, Orviston, Palau, 5453",
            "about": "Sit anim officia consequat velit ut do non nostrud esse officia culpa reprehenderit. Proident velit proident aliqua nulla fugiat ea dolor laboris officia. Cillum fugiat velit aliqua ullamco ipsum non non tempor ullamco.\r\n",
            "registered": "2017-11-13T11:48:59 +05:00",
            "latitude": 62.190713,
            "longitude": 46.622887,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d234a2894cca7151017d",
            "index": 15,
            "guid": "ab45c179-77ca-4e95-9aa0-bdc57adc409d",
            "isActive": false,
            "balance": "$2,152.65",
            "age": 36,
            "eyeColor": "green",
            "name": "Alston Small",
            "gender": "male",
            "company": "DIGIQUE",
            "email": "alstonsmall@digique.com",
            "phone": "+1 (835) 449-3745",
            "address": "544 Bath Avenue, Carlton, Wyoming, 9869",
            "about": "Cupidatat labore ut minim elit Lorem voluptate ea reprehenderit. Laborum minim adipisicing tempor sit commodo sit deserunt ut id voluptate id et pariatur anim. Ad reprehenderit est exercitation do amet commodo pariatur nostrud adipisicing Lorem.\r\n",
            "registered": "2020-04-16T08:34:52 +04:00",
            "latitude": 59.488536,
            "longitude": 152.385349,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d2341b62e035d9cb29f5",
            "index": 16,
            "guid": "d9f76230-b0fc-4c60-a016-8ae115ea285b",
            "isActive": false,
            "balance": "$1,765.47",
            "age": 29,
            "eyeColor": "blue",
            "name": "Marylou Mccormick",
            "gender": "female",
            "company": "STUCCO",
            "email": "maryloumccormick@stucco.com",
            "phone": "+1 (892) 509-3899",
            "address": "616 Schenck Court, Foscoe, South Carolina, 1700",
            "about": "Incididunt magna velit eiusmod velit. Quis culpa non tempor minim excepteur cupidatat nisi Lorem consectetur nostrud ullamco eu. Laborum ut elit magna mollit eu duis. Non qui est sint veniam ea dolore. Consectetur nisi proident enim aliqua esse irure officia magna ad. Ipsum pariatur commodo eiusmod magna sint culpa ex.\r\n",
            "registered": "2016-07-02T10:48:58 +04:00",
            "latitude": 42.193028,
            "longitude": -3.751722,
            "favoriteFruit": "apple"
          },
          {
            "_id": "6213d234d5ed51f3702da554",
            "index": 17,
            "guid": "236343dc-4fdc-4801-9433-1653df32a01f",
            "isActive": false,
            "balance": "$3,095.70",
            "age": 40,
            "eyeColor": "blue",
            "name": "Oneil Fowler",
            "gender": "male",
            "company": "SUREPLEX",
            "email": "oneilfowler@sureplex.com",
            "phone": "+1 (950) 544-2181",
            "address": "946 Strauss Street, Epworth, Vermont, 3012",
            "about": "Ullamco enim minim anim ullamco ullamco consectetur in. Duis incididunt id ea incididunt veniam elit qui nulla dolor. Do aliqua mollit eu ipsum sint dolore.\r\n",
            "registered": "2020-10-09T05:04:25 +04:00",
            "latitude": -83.169736,
            "longitude": 118.335802,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d2341bbb67dcd0d41186",
            "index": 18,
            "guid": "af09594a-985c-4f12-a046-45f371f063a5",
            "isActive": false,
            "balance": "$1,016.70",
            "age": 25,
            "eyeColor": "brown",
            "name": "Levy Whitehead",
            "gender": "male",
            "company": "GEEKOLA",
            "email": "levywhitehead@geekola.com",
            "phone": "+1 (976) 400-3360",
            "address": "597 Seacoast Terrace, Trail, Wisconsin, 8919",
            "about": "Veniam aute nulla anim mollit ad deserunt nisi ut amet. Mollit sint voluptate qui culpa nostrud et occaecat exercitation. Tempor aute est aute culpa aliqua. Tempor nulla est est nostrud tempor. Officia ut mollit id pariatur ea reprehenderit aute anim. Cupidatat esse quis incididunt mollit nisi aliquip.\r\n",
            "registered": "2018-08-15T08:34:23 +04:00",
            "latitude": -56.28155,
            "longitude": 152.737913,
            "favoriteFruit": "strawberry"
          },
          {
            "_id": "6213d2342198b005a5b64f54",
            "index": 19,
            "guid": "69453b64-726a-4d2d-a64c-82644033c5ae",
            "isActive": true,
            "balance": "$2,401.24",
            "age": 21,
            "eyeColor": "green",
            "name": "Mariana Richard",
            "gender": "female",
            "company": "NIQUENT",
            "email": "marianarichard@niquent.com",
            "phone": "+1 (954) 470-3407",
            "address": "315 Martense Street, Summerfield, Marshall Islands, 8653",
            "about": "Qui adipisicing minim duis laboris aliquip qui est et mollit anim. Nisi quis esse occaecat deserunt enim. Irure eiusmod velit in veniam amet quis. Est ipsum nostrud duis tempor deserunt. Voluptate in Lorem id tempor do quis. Amet exercitation labore enim ut in ipsum pariatur. Do ullamco minim qui ut cupidatat labore dolore qui id aliquip ullamco dolor cupidatat.\r\n",
            "registered": "2021-04-20T06:23:29 +04:00",
            "latitude": 7.25152,
            "longitude": -31.069078,
            "favoriteFruit": "apple"
          }
        ]}
      />
    </div>)
}
